# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_GERANT:      ROLE_GERANT
        ROLE_CANDIDAT:    ROLE_CLIENT
        ROLE_MONITEUR:    ROLE_MONITEUR
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern:
            form_login:
                provider: fos_userbundle
                always_use_default_target_path: false
                success_handler: redirect.after.login

            logout:       true
            anonymous:    true


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/profile/, role: ROLE_CLIENT }
        - { path: ^/user, role: ROLE_CLIENT }