my_app_carte_homepage:
    path:     /
    defaults: { _controller: MyAppCarteBundle:Default:index }
ajouter carte:
     path:     /admin/ajoutCarte
     defaults: { _controller: MyAppCarteBundle:recharge:AjoutCarteRecharfe }
affiche carte:
     path:     /admin/afficheCarte
     defaults: { _controller: MyAppCarteBundle:recharge:listCarteRecharge }
supprimer carte:
     path:     /admin/supprimerCarte/{numRecharge}
     defaults: { _controller: MyAppCarteBundle:recharge:supprimerCarte }
modifier carte:
     path:     /admin/modifierCarte/{numRecharge}
     defaults: { _controller: MyAppCarteBundle:recharge:modifierCarte }
recharge carte:
     path:     /recharger
     defaults: { _controller: MyAppCarteBundle:recharge:Recharger }


