my_app_user_homepage:
    path:     /home
    defaults: { _controller: MyAppUserBundle:Default:home }
my_app_back_page:
    path:     /back
    defaults: { _controller: MyAppUserBundle:Default:Back }
my_app_gerant_page:
    path:     /gerant
    defaults: { _controller: MyAppUserBundle:Default:gerant }
my_app_candidat_page:
    path:     /client
    defaults: { _controller: MyAppUserBundle:Default:Client }
my_app_moniteur_page:
    path:     /moniteur
    defaults: { _controller: MyAppUserBundle:Default:Moniteur }
my_app_admin_page:
    path:     /admin
    defaults: { _controller: MyAppUserBundle:Default:Admin }