my_app_seance_homepage:
    path:     /
    defaults: { _controller: MyAppGestionSeanceBundle:Default:index }
lsitSeance:
    path:     /listSeance
    defaults: { _controller: MyAppGestionSeanceBundle:Default:listSeance }
ajoutSeance:
    path:     /ajoutSeance
    defaults: { _controller: MyAppGestionSeanceBundle:Default:AjoutSeance }
lsitSeance2:
    path:     /listSeance2
    defaults: { _controller: MyAppGestionSeanceBundle:Default:findMoniteurDQL }
modifSeance:
    path:     /modif/{id}
    defaults: { _controller: MyAppGestionSeanceBundle:Default:modifierSeance}
SupprimerSeance:
    path:     /supp/{id}
    defaults: { _controller: MyAppGestionSeanceBundle:Default:SupprimerSeance}
MesSeances:
    path:     /myplaning
    defaults: { _controller: MyAppGestionSeanceBundle:Default:Planinig}
PDF:
      path:     /PDF/{id}
      defaults: { _controller:   MyAppGestionSeanceBundle:Default:pdf}
recherche:
      path:     /recherche/{motcle}
      defaults: { _controller:   MyAppGestionSeanceBundle:Default:rechercherAjax }
      requirements:
          format: json
MesSeancesMoniteur:
    path:     /myplaningmoniteur
    defaults: { _controller: MyAppGestionSeanceBundle:Default:PlaninigM}
PDFM:
      path:     /PDFM/{id}
      defaults: { _controller:   MyAppGestionSeanceBundle:Default:pdfM}